# Generated by Django 5.2.5 on 2025-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jobtype', models.CharField(choices=[('part time', 'part time'), ('Full time', 'Full time')], max_length=15)),
                ('Description', models.TextField(max_length=1000)),
                ('vacancy', models.IntegerField(default=1)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
