# Generated by Django 5.2.5 on 2025-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
